### ISSUE TITLE
grunt v1.0.0 breaks grunt-durandal

### ISSUE THREAD

**Issue by Ld00d** [spatools/grunt-durandal#6]
My package.json specifies grunt >=0.4.0 so it updated to the latest. This resulted in the following error:

> Error: Error: Module loading did not complete for: durandal/plugins/history, durandal/plugins/http, durandal/plugins/router
> The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:
> 
> /Users/fpoole/Projects/msc/mov/services/NoteAssistService/target-grunt/bower_components/durandal/js/plugins/history.js: durandal/plugins/history, plugins/history
> /Users/fpoole/Projects/msc/mov/services/NoteAssistService/target-grunt/bower_components/durandal/js/plugins/router.js: durandal/plugins/router, plugins/router
> /Users/fpoole/Projects/msc/mov/services/NoteAssistService/target-grunt/bower_components/durandal/js/plugins/http.js: durandal/plugins/http, plugins/http
> Warning: Task "durandal:dist" failed. Use --force to continue.

I think I've tracked it down to line 134 of tasks/build-durandal.js:

`file.src.forEach(_.partial(includePath, config.include, config));`

v1.0.0 updated lodash:

> - `lodash` was upgraded to `~4.3.0`. Many changes have occurred. Some of which
>       that directly effect Grunt are `grunt.util._.template()` returns a compile
>       function and `grunt.util._.flatten` no longer flattens deeply.
>       `grunt.util._` is deprecated and we highly encourage you to
>       `npm install lodash` and `var _ = require('lodash')` to use `lodash`.
>       Please see the lodash changelog for a full list of changes: https://github.com/lodash/lodash/wiki/Changelog

**Comment by Ld00d** [comment]
Looks like the fix is to remove durandal from the "src":

`            dist: {
                src: [
                    'app/**/*.*',
                    'scripts/durandal/**/*.*'
                ],`

should be 

`            dist: {
                src: [
                    'app/**/*.*'
                ],`

**Comment by SomaticIT** [comment]
Hi,
You were right, the error was due to `lodash` update.
I also added `lodash` as a dependency to avoid deprecation.

I fixed the issue and published a version `0.2.0` in [npm](https://www.npmjs.com/package/grunt-durandal).

Thanks.
